alias pr='poetry run'
alias ci='pr ci'
alias cis='ci ssm'
alias cise='cis ec2'
alias cisec='cise connect'
alias connect='cisec'
alias cisel='cise list-instances'
alias cisels='cise list-sessions'
alias ciesc='cise close-current-user-sessions'

alias ciss='cis sftp'
alias cissc='ciss create-user'
alias cisscr='ciss create-user-rdp'
alias cisss='ciss switch-user-to-rdp'
alias cissd='ciss delete-user'
alias cissp='ciss change-password'